### ISSUE TITLE
Support for block creation

### ISSUE THREAD

**Issue by jpeeg** [PrefectHQ/terraform-provider-prefect#126]
It would be really great if blocks could be created via Terraform. Currently we have various GCP service accounts we need prefect to use, which means we have to manually generate and download the key for each service account, create a prefect block, and paste the key in. We need to do this for many different service accounts across multiple workspaces.

A smoother alternative would be when we create the GCP service accounts in terraform we can also generate the keys and pass them as an input to e.g. a terraform module which is responsible for creating "GCP Credentials" blocks.

Thank you!

**Comment by iotmani** [comment]
Hey @desertaxle, do you want to take this ticket as per our earlier discussion? Or link it to an existing one if you have one.

**Comment by diogo-coalition** [comment]
+1

**Comment by taylor-curran** [comment]
I have a plus one from a customer on this request.

**Comment by oieduardorabelo** [comment]
any roadmap to support this feature?

i have a similar user case:

- multiple tenants in aws require multiple blocks in prefect
- for each tenant, i create a process + aws credentials block

current solution is calling the prefect rest api post-terraform apply

it works, but ideally, everything should be handled in terraform

**Comment by mitchnielsen** [comment]
👋🏼 Thanks everyone for reaching out. We're actively discussing this internally and deciding how best to implement it. We should have a more detailed update either this week or next.

**Comment by mitchnielsen** [comment]
We're starting to iterate on blocks support now 🎉 You can keep an eye on work by [searching for "Blocks Support" issues](https://github.com/PrefectHQ/terraform-provider-prefect/issues?q=is%3Aissue+is%3Aopen+%22BlockS+Support%22).

**Comment by mitchnielsen** [comment]
Checking in: we've [completed](https://github.com/PrefectHQ/terraform-provider-prefect/issues?q=is%3Aissue+%22Blocks+Support%22+is%3Aclosed) all of the issues we created for addressing Block support. We're going to do some more testing and dogfooding of this internally and will follow up when we cut a public release.

**Comment by oieduardorabelo** [comment]
thanks amazing, thanks @mitchnielsen 

i'll bring that up to our backlog asap

looking forward to REMOVE code 🚀

**Comment by parkedwards** [comment]
hey everyone - [v2.0.0 is out](https://github.com/PrefectHQ/terraform-provider-prefect/releases/tag/v2.0.0), which adds Blocks support to the Provider

https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/block
