### ISSUE TITLE
Prefect Cloud returning 403 when Automations are being set

### ISSUE THREAD

**Issue by akmukherjee** [PrefectHQ/terraform-provider-prefect#137]
We are getting an error when setting up Automations in our Account. It looks like Automations is not enabled from the Chrome Dev Tools response which returns a 403 with an error message when Automations are being set. Screenshots are attached.
<img width="1920" alt="Screenshot 2024-01-04 at 1 23 42 PM" src="https://github.com/PrefectHQ/terraform-provider-prefect/assets/6787494/614f0bd7-1121-48db-be45-523872e43b55">
<img width="1920" alt="Screenshot 2024-01-04 at 1 23 57 PM" src="https://github.com/PrefectHQ/terraform-provider-prefect/assets/6787494/9beda905-0e85-473f-859a-0d0f3cfaf6d8">

**Comment by parkedwards** [comment]
hey @akmukherjee - could you provide your Prefect Cloud account id? Your account likely has this feature disabled

**Comment by akmukherjee** [comment]
Yeah, it has been fixed. Thanks a bunch!
Very Respectfully,
Amit
