### ISSUE TITLE
Blocks Support: Create `prefect_block` resource - Tests + Docs

### ISSUE THREAD

**Issue by parkedwards** [PrefectHQ/terraform-provider-prefect#183]
https://www.notion.so/prefect/Design-Block-support-in-the-Terraform-Provider-ae2ea25a18864de9b51b8aa06af9486b?pvs=4

```hcl
resource "prefect_block" "datadog_api_key" {
	name = "datadog-api-key"
	type = "secret"
	data = jsonencode({
		value = var.datadog_api_key
	})
}
```

Located in `internal/provider/resources/block.go`

Also, be sure to include acceptance tests and docs
* `/internal/provider/resources/block_test.go`
* `/examples/resources/prefect_block`

**Comment by mitchnielsen** [comment]
I'll pick this up for now as I'd like to learn how this part works, but feel free to reassign if needed.

**Comment by parkedwards** [comment]
ah @mitchnielsen i just saw you grabbed it, sorry man. in https://github.com/PrefectHQ/terraform-provider-prefect/pull/196 i added some foundations for a `block_test.go` file, so there should be some stuff for us to look at for followup PRs

i couldn't quite get this to work, i think we might be missing some logic to gracefully handle the different URL schemas between open source and cloud https://github.com/PrefectHQ/terraform-provider-prefect/issues/192

**Comment by mitchnielsen** [comment]
No worries at all, sounds good! And good to know.
