### ISSUE TITLE
422 Response on Account resource update

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/terraform-provider-prefect#227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

```
Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/prefecthq/prefect v2.0.0
```

### Affected Resource(s)

* prefect_account

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
resource "prefect_account" "test_tf_account" {
  handle        = "robertprefectio"
  name          = "robertprefectio"
  billing_email = "test@prefect.io"
  allow_public_workspaces = false
}
```

### Debug Output

```
prefect_account.test_tf_account: Modifying... [id=a0461d35-5351-4284-bb93-de0975f46b7d]
╷
│ Error: Error during update Account
│ 
│   with prefect_account.test_tf_account,
│   on resource.tf line 9, in resource "prefect_account" "test_tf_account":
│    9: resource "prefect_account" "test_tf_account" {
│ 
│ Could not update Account, unexpected error: status code 422 Unprocessable Entity, error={"exception_message":"Invalid request
│ received.","exception_detail":[{"loc":["body","allow_public_workspaces"],"msg":"extra fields not
│ permitted","type":"value_error.extra"}],"request_body":{"name":"robertprefectio","handle":"robertprefectio","location":null,"link":null,"auth_expiration_seconds":null,"allow_public_workspaces":false,"billing_email":"test@prefect.io"}}
```

### Expected Behavior

Prefect account should be updated with the billing_email and allow_public_workspaces fields. 

### Actual Behavior

Unable to update Prefect account fields due to 422 error on tf apply. 

### Steps to Reproduce

1.  terraform import prefect_account.test_tf_account a0461d35-5351-4284-bb93-de0975f46b7d
2. Specify prefect_account resource (see code above) 
3. `terraform apply`

### References

Looks like the 'allow_public_workspaces' field for the update accounts API call is under a 'settings' field now. Most likely just needs a quick update to reflect the new nested structure. 

<img width="1084" alt="image" src="https://github.com/PrefectHQ/terraform-provider-prefect/assets/104510333/984255eb-ffbe-46ed-bea4-25f62e5a7bc2">

* #0000

**Comment by parkedwards** [comment]
thanks @robfreedy - we'll take a look

**Comment by mitchnielsen** [comment]
@robfreedy - this should be fixed now 👍🏼 

We haven't cut a release yet, but you can:
1. Clone this project and switch to the directory
2. Run `go install`
3. Copy the `~/.terraformrc` file to your system
4. Run your `terraform` commands

**Comment by mitchnielsen** [comment]
@parkedwards - is it worth considering a patch release here? If so, what does that process look like? (I can kick it off)
