### ISSUE TITLE
prefect block types inspect not working

### ISSUE THREAD

**Issue by patonavarro** [PrefectHQ/terraform-provider-prefect#239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
1.9.3

### Affected Resource(s)

* prefect_block

### Terraform Configuration Files

command: prefect block types inspect <slug>

### Expected Behavior

Use prefect block types ls to view all available Block type slugs, which is used in the type_slug attribute. Use prefect block types inspect <slug> to view the data schema for a given Block type. Use this to construct the data attribute value (as JSON string).

### Actual Behavior

Just a message without schema

### Steps to Reproduce

command: prefect block types inspect <slug>

**Comment by parkedwards** [comment]
hey @patonavarro , couple followup questions:

what's your prefect CLI version?
```
➜ prefect --version
```

when you make your inspect command, are you passing in a type slug?

```
➜ prefect block type inspect <slug>
```

in order to find all available slugs, try:

```
➜ prefect block type ls
```

**Comment by mitchnielsen** [comment]
I noticed the other day that you need at least version 3.0.0rc to have the feature merged in https://github.com/PrefectHQ/prefect/commit/0b359a7a03daab3021402869c2cd7dc79049f5d5:

```
~/code/github.com/prefecthq/prefect/main
$ git tag --contains 0b359a7a03daab3021402869c2cd7dc79049f5d5 | grep -v 'prefect-'
3.0.0rc1
3.0.0rc10
3.0.0rc11
3.0.0rc12
3.0.0rc13
3.0.0rc14
3.0.0rc15
3.0.0rc2
3.0.0rc3
3.0.0rc4
3.0.0rc5
3.0.0rc6
3.0.0rc7
3.0.0rc8
3.0.0rc9
```
