### ISSUE TITLE
Error in acceptance tests: "Error during create Workspace: 503 Service Unavailable"

### ISSUE THREAD

**Issue by mitchnielsen** [PrefectHQ/terraform-provider-prefect#241]
## Summary

We've been seeing consistent failures in acceptance tests:

```
Run make testacc
TF_ACC=1 make test
make[1]: Entering directory '/home/runner/work/terraform-provider-prefect/terraform-provider-prefect'
gotestsum --max-fails=50 ./...
∅  .
∅  internal/api
∅  internal/client
∅  internal/provider
∅  internal/provider/customtypes
∅  internal/provider/helpers
∅  internal/testutils
∅  internal/utils
✓  internal/provider/datasources (5.17[8](https://github.com/PrefectHQ/terraform-provider-prefect/actions/runs/10379690891/job/28738291855?pr=202#step:7:9)s)
✖  internal/provider/resources (10.815s)
=== Failed
=== FAIL: internal/provider/resources TestAccResource_flow (0.44s)
    flow_test.go:34: Step 1/3 error: Error running apply: exit status 1
        
        Error: Error during create Workspace
        
          with prefect_workspace.workspace,
          on terraform_plugin_test.tf line 12, in resource "prefect_workspace" "workspace":
          12: resource "prefect_workspace" "workspace" {
        
        Could not create Workspace, unexpected error: status code 503 Service
        Unavailable, error={"exception_message":"Service Unavailable"}
DONE 23 tests, 1 failure in 12.766s
make[1]: *** [Makefile:3[9](https://github.com/PrefectHQ/terraform-provider-prefect/actions/runs/10379690891/job/28738291855?pr=202#step:7:10): test] Error 1
make[1]: Leaving directory '/home/runner/work/terraform-provider-prefect/terraform-provider-prefect'
make: *** [Makefile:45: testacc] Error 2
```

Examples:
- Failure in `flow` test: https://github.com/PrefectHQ/terraform-provider-prefect/actions/runs/10379690891/job/28738291855?pr=202
- Failure in `workspace` test: https://github.com/PrefectHQ/terraform-provider-prefect/actions/runs/10377092449/job/28730515383

We found a [trace in DataDog](https://app.datadoghq.com/apm/traces?query=env%3Astg%20%40http.path_group%3A%22%2Fapi%2Faccounts%2F%3F%2Fworkspaces%2F%22&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=1291907203443865151&spanType=all&timeHint=1723579537845&trace=AgAAAZFNWJm1JyuwgAAAAAAAAAAYAAAAAEFaRk5XU21vQUFBWlI3T3lQVlZxTzRtbAAAACQAAAAAMDE5MTRkNTgtZDk0ZC00ZWMyLTk1YTktNDRlZDU3M2IyNmQ2&traceID=37f7f8754603229ca58993512187e565&view=spans&start=1723409843547&end=1723582643547&paused=false):

```
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.SerializationError'>: could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during conflict out checking.
HINT:  The transaction might succeed if retried.
```

**Comment by mitchnielsen** [comment]
I posted in `#platform-backend` asking for some insight. Eddie has a feeling we're seeing this because Prefect isn't correctly handling several simultaneous requests to create workspaces at the same time.

**Comment by mitchnielsen** [comment]
There are currently 3 ephemeral workspaces being created each time Acceptance Tests run:

```
$ rg 'EphemeralWorkspace' **/*/*_test.go
internal/provider/resources/block_test.go:36:43:        workspace, workspaceName := testutils.NewEphemeralWorkspace()
internal/provider/resources/work_pool_test.go:30:43:    workspace, workspaceName := testutils.NewEphemeralWorkspace()
internal/provider/resources/variable_test.go:51:43:     workspace, workspaceName := testutils.NewEphemeralWorkspace()
```

**Comment by zangell44** [comment]
I suspect the root cause of the issue is the small size (42 rows) of our `workspace_role` table is forcing a seq scan when we lookup workspace roles. Since multiple transactions are performing this seq scan at close the same time, they both end up with an `SIReadLock` on the entire table

Good write up here https://stackoverflow.com/questions/42288808/why-does-postgresql-serializable-transaction-think-this-as-conflict

**Comment by mitchnielsen** [comment]
Zach and I caught up on this in Slack:
- Was still seeing 503s after the change above. Zach is looking into this further.
- In the meantime, Zach suggested adding retries and mentioned that `409`s will indicate the Workspace already exist. I pushed https://github.com/PrefectHQ/terraform-provider-prefect/pull/242 to add that.

**Comment by mitchnielsen** [comment]
With the retry mitigation in place, we haven't seen this since. Will close this for now - upstream issue is being tracked in https://linear.app/prefect/issue/CLOUD-95/concurrent-workspace-creation-results-in-database-locks.
