### ISSUE TITLE
Support cloud_run_v2 for the worker_metadata data source

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/terraform-provider-prefect#276]
The `worker_metadata` datasource supports `cloud-run` and `cloud-run:push` but not the equivalent `cloud-run-v2` and `cloud-run-v2:push`. We should support `v2` as well.

### Version

```
Terraform v1.9.7
on darwin_arm64
+ provider registry.terraform.io/prefecthq/prefect v2.2.3
```

**Comment by mitchnielsen** [comment]
@jimid27 @jamiezieziula labeling this up as a good first issue. I believe we'll just need to add a new line for these in [this map](https://github.com/PrefectHQ/terraform-provider-prefect/blob/5933437c78cb50f7fc87e98b53e2095412992961/internal/provider/datasources/worker_metadata.go#L159-L185). You can update the test as well in `worker_metadata_test.go` to confirm the new fields are set.
