### ISSUE TITLE
Add the ability to create rate limit and concurrency through terraform

### ISSUE THREAD

**Issue by david-gang** [PrefectHQ/terraform-provider-prefect#278]
As explained [here](https://docs.prefect.io/3.0/develop/global-concurrency-limits) there is an option to create global concurrency and rate limits through the ui and cli. I looked and did not find a way to do it through terraform
Could this option please be added?

**Comment by mitchnielsen** [comment]
Hi @david-gang, thanks for reaching out. Sounds like a fair request - I opened https://github.com/PrefectHQ/terraform-provider-prefect/issues/280 and attached it to our [milestone for parity with the Prefect API](https://github.com/PrefectHQ/terraform-provider-prefect/milestone/1).
