### ISSUE TITLE
Extract Go Client SDK into separate module

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/terraform-provider-prefect#28]
The Go Client SDK included in this provider is not Terraform-specific, and we can refactor it into a separate Go module for use in other applications. We could then also simplify much of this code by using code generation, related to #13

**Comment by mitchnielsen** [comment]
@parkedwards - is this already complete given that we have:

https://github.com/PrefectHQ/terraform-provider-prefect/tree/main/internal/client

Or is `Go Client SDK` referring to something else here?
