### ISSUE TITLE
Prefect Terraform provider errors with 404 when trying to create a new work pool

### ISSUE THREAD

**Issue by jtbaker** [PrefectHQ/terraform-provider-prefect#281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
---

While working on a project, I ran across this issue when trying to provision a work pool via IAC. I've distilled it down to a minimum reproducible example here. Seems like maybe there is a mismatch on what is expected between the TF provider and the Prefect API. Notably (in the linked debug log below), the prefect API URL it seems to expect is: `prefect_endpoint=https://api.prefect.cloud/api/accounts/ACCOUNT_ID/workspaces/WORKSPACE_ID/api`

**^ note the trailing `/api` here**. I don't see this sub-route documented anywhere in the [API Docs](https://app.prefect.cloud/api/docs#tag/Workspaces) and wonder if it could be the cause of the problem.

IIt seems to be getting appended to the url [here](https://github.com/PrefectHQ/terraform-provider-prefect/blob/main/internal/provider/provider.go#L130-L132) in the provider.
### Terraform Version

Terraform v1.9.7
on darwin_arm64
+ provider registry.terraform.io/prefecthq/prefect v2.3.0
### Affected Resource(s)
```
prefect_v2.3.0
```
### Terraform Configuration Files

main.tf
```tf
terraform {
  required_providers {
    prefect = {
      source = "prefecthq/prefect"
      version = "2.3.0"
    }
  }
}

provider "prefect" {
  api_key = var.prefect_api_key
  account_id = var.prefect_account_id
}


resource "prefect_work_pool" "test_work_pool" {
  name = "test-work-pool"
  type = "kubernetes"
}
```

variables.tf
```
variable "prefect_api_key" {
  description = "Prefect Cloud API key"
  type        = string
}

variable "prefect_account_id" {
  description = "Prefect Account ID"
  type        = string
}
```

### Debug Output

```
╷
│ Error: Error during create Work Pool
│ 
│   with prefect_work_pool.test_work_pool,
│   on main.tf line 16, in resource "prefect_work_pool" "test_work_pool":
│   16: resource "prefect_work_pool" "test_work_pool" {
│ 
│ Could not create Work Pool, unexpected error: status code 404 Not Found, error=
```

https://gist.github.com/jtbaker/a83908f7027f10a24f83d797567d56e1

### Expected Behavior

Create a new work pool

### Actual Behavior

Errored due to 404 in provider

### Steps to Reproduce

```sh
export TF_VAR_prefect_api_key=$PREFECT_API_KEY
export TF_VAR_prefect_account_id=$PREFECT_ACCOUNT_ID

terraform plan
terraform apply
```

### References

* #260 It seems like my issue may be related to this documented issue. But notably, my issue occurs when a work pool hasn't been created yet.

**Comment by mitchnielsen** [comment]
Thanks for reaching out @jtbaker - I believe I found the root cause here.

In Prefect Cloud, to create a workspace you need both account ID and workspace ID ([API docs](https://app.prefect.cloud/api/docs#tag/Work-Pools/operation/create_work_pool_api_accounts__account_id__workspaces__workspace_id__work_pools__post)):

<img width="655" alt="image" src="https://github.com/user-attachments/assets/e5ea0133-8c8d-487a-825b-f6ddf8eb0ee1">

In your config, you've only defined account ID - which somewhat makes sense, since that's the minimal example from the docs and the work pool resource docs say Workspace ID is optional. And it _is_ optional, but that's mostly because you wouldn't have the concept of a workspace ID in the open source version of Prefect.

I think we can make this clearer in the docs, and maybe even return an error in the scenario that you are in Prefect Cloud and the specific resource requires a workspace ID to be configured. Let me chew on this and I'll follow up here with any updates.

**Comment by mitchnielsen** [comment]
By the way, the workaround in the meantime should just be to set `workspace_id` on either the `provider` or the `work_pool`.

**Comment by jtbaker** [comment]
> Thanks for reaching out @jtbaker - I believe I found the root cause here.
> 
> In Prefect Cloud, to create a workspace you need both account ID and workspace ID ([API docs](https://app.prefect.cloud/api/docs#tag/Work-Pools/operation/create_work_pool_api_accounts__account_id__workspaces__workspace_id__work_pools__post)):
> 
> In your config, you've only defined account ID - which somewhat makes sense, since that's the minimal example from the docs and the work pool resource docs say Workspace ID is optional. And it _is_ optional, but that's mostly because you wouldn't have the concept of a workspace ID in the open source version of Prefect.
> 
> I think we can make this clearer in the docs, and maybe even return an error in the scenario that you are in Prefect Cloud and the specific resource requires a workspace ID to be configured. Let me chew on this and I'll follow up here with any updates.

Hey @mitchnielsen, I actually tried using the workspace id in both places in my real use case, but didn't include it in my reproducible example as it didn't seem to make a difference. With an updated

variables.tf
```tf
variable "prefect_api_key" {
  description = "Prefect Cloud API key"
  type        = string
}

variable "prefect_account_id" {
  description = "Prefect Account ID"
  type        = string
}


variable "prefect_workspace_id" {
  description = "Prefect Workspace ID"
  type        = string
}
```

and 

main.tf
```tf
terraform {
  required_providers {
    prefect = {
      source = "prefecthq/prefect"
      version = "2.3.0"
    }
  }
}

provider "prefect" {
  api_key = var.prefect_api_key
  account_id = var.prefect_account_id
  workspace_id = var.prefect_workspace_id
}


resource "prefect_work_pool" "test_work_pool" {
  name = "test-work-pool"
  type = "kubernetes"
  workspace_id = var.prefect_workspace_id
}
```

```
export TF_VAR_prefect_workspace_id=<my-workspace-id>
terraform plan
```

I get this message from `terraform plan`, confirming that the workspace id is set in the configuration:
```
  # prefect_work_pool.test_work_pool will be created
  + resource "prefect_work_pool" "test_work_pool" {
      + base_job_template = jsonencode({})
      + created           = (known after apply)
      + default_queue_id  = (known after apply)
      + id                = (known after apply)
      + name              = "test-work-pool"
      + paused            = false
      + type              = "kubernetes"
      + updated           = (known after apply)
      + workspace_id      = "<my-workspace-id>"
    }
```

but still seem the same error after `terraform apply`

```
2024-10-16T11:39:41.071-0500 [ERROR] vertex "prefect_work_pool.test_work_pool" error: Error during create Work Pool
╷
│ Error: Error during create Work Pool
│ 
│   with prefect_work_pool.test_work_pool,
│   on main.tf line 17, in resource "prefect_work_pool" "test_work_pool":
│   17: resource "prefect_work_pool" "test_work_pool" {
│ 
│ Could not create Work Pool, unexpected error: status code 404 Not Found, error=
```

Do you have a sandbox workspace you could test these terraform configs out and seeing if they reproduce for you? I've blown away all my `.terraform` directories and files and started the state fresh with `terraform init` a few times and still seeing the error.

**Comment by mitchnielsen** [comment]
Interesting 🤔 I just took this exact example and had no problems creating and destroying the work pool.

Just to make sure:
1. You are setting the `account_id` and `api_key` at some point, right? I only ask because your latest comment only shows you setting the `workspace_id`.
2. Does there happen to be a work pool by that name already? I'm wondering if you're running into https://github.com/PrefectHQ/terraform-provider-prefect/issues/260, because this looks very similar.

You could try running `TF_LOG=DEBUG terraform apply` so we can get some debug output and look further.

**Comment by jtbaker** [comment]
@mitchnielsen helped me rule out some issues, it seemed like my shell environment had gotten borked somehow and was causing my issues. When I got a fresh shell the provider worked as expected. Closing this one out, thanks for the assistance!
