### ISSUE TITLE
Prefect Blocks 405 Response

### ISSUE THREAD

**Issue by quoimec** [PrefectHQ/terraform-provider-prefect#284]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v1.9.8
on darwin_arm64

### Affected Resource(s)

* `prefect_block`

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    prefect = {
      source = "prefecthq/prefect"
    }
  }
}

provider "prefect" {
  endpoint    = "https://my-prefect-server.com/api"
}

resource "prefect_work_pool" "example" {
  name        = "my-work-pool"
  type        = "kubernetes"
  description = "example work pool"
  paused      = true
}

resource "prefect_block" "secret" {
  name      = "food"
  type_slug = "secret"

  data = jsonencode({
    "name"   = "mine"
    "target" = "prefect-dbt-profile"
  })
}
```

### Output

```
prefect_block.secret: Creating...
╷
│ Error: Error during create Block Document
│ 
│   with prefect_block.secret,
│   on main.tf line 13, in resource "prefect_block" "secret":
│   13: resource "prefect_block" "secret" {
│ 
│ Could not create Block Document, unexpected error: status code 405 Method Not Allowed, error={"detail":"Method Not Allowed"}
```

### Behavior

I am trying to create a prefect block on my self-hosted server. I am only getting a 405 response back though. I am able to create work pools, variables etc on the server using terraform. Blocks just return a 405. Are blocks a cloud-only resource? I have only taken example resources from the documentation.

**Comment by mitchnielsen** [comment]
Hi @quoimec, thanks for reaching out. I wasn't actually able to replicate the error - I took your configuration and applied it against both a Prefect 2 and Prefect 3 instance and it created the work pool and block.

Could you please share the following:
1. Version of Prefect you're using
1. Version of the Prefect Terraform provider you're using
1. Any relevant output from`TF_LOG=debug terraform apply` (just make sure nothing secret is published here)

Thanks!

**Comment by quoimec** [comment]
Hey Mitch,

- The version of Prefect that I am running currently is 3.0.10. But yesterday as part of debugging, I downgraded to the latest v2 release. Same issue. 
- The provider version I am using is 2.3.1
- I was having a look at this output yesterday too, there's not much here either unfortunately:

```
prefect_block.secret: Creating...
2024-10-22T06:20:50.507+1100 [INFO]  Starting apply for prefect_block.secret
2024-10-22T06:20:50.507+1100 [DEBUG] prefect_block.secret: applying the planned Create change
2024-10-22T06:20:50.808+1100 [ERROR] provider.terraform-provider-prefect_v2.3.1: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/diag/diagnostics.go:58 diagnostic_detail="Could not create Block Document, unexpected error: status code 405 Method Not Allowed, error={\"detail\":\"Method Not Allowed\"}" diagnostic_summary="Error during create Block Document" tf_provider_addr=registry.terraform.io/prefecthq/prefect tf_req_id=1f7dfeeb-c50d-08cc-c20a-4285765278e8 tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=6.6 tf_resource_type=prefect_block timestamp="2024-10-22T06:20:50.806+1100"

```

**Comment by quoimec** [comment]
Is there something I can change on the prefect server end to see more logs when the resource is attempting to be created?

Another piece of context - because self hosted has no auth, my server is behind an IP whitelist. I assume the block resource isn't doing something weird and doing something that sends a request from an IP that is not my own right?

**Comment by mitchnielsen** [comment]
Are you seeing anything in the debug output that shows which endpoint it's trying to hit? That'd help debug why we're getting that response.

This almost looks similar to https://github.com/PrefectHQ/prefect/issues/10193 🤔 Any chance you could check your state with `terraform state show <resource>` or try this with a fresh Terraform state?

> Is there something I can change on the prefect server end to see more logs when the resource is attempting to be created?

You should be able to set `PREFECT_LOGGING_SERVER_LEVEL`, which is by default `WARNING` I believe. If you're deploying with the Helm chart, the value is `loggingLevel`.

> Another piece of context - because self hosted has no auth, my server is behind an IP whitelist. I assume the block resource isn't doing something weird and doing something that sends a request from an IP that is not my own right?

I wouldn't suspect that to cause a problem, but if we run out of options maybe we can try reaching it directly (temporarily).

**Comment by parkedwards** [comment]
hey @quoimec - could you also share any configurations around your prefect-server installation (with any sensitive information redacted/removed)?  [Are you using one of our prefect-helm charts](https://github.com/PrefectHQ/prefect-helm) - if so, could you share a values file?  If not, could you share any environment variables and relevant settings?

**Comment by quoimec** [comment]
@mitchnielsen This is from a totally fresh terraform state, there are no existing resources on the server or in the state. I have also upped the logging in prefect to DEBUG but saw nothing in the logs during an attempted apply. Interestingly when I apply a work pool, I also don't see any logs regarding creation, just that it's coming online.

```tf
resource "prefect_work_pool" "example" {
  name         = "my-work-pool"
  type         = "kubernetes"
  paused       = false
}
```

```
00:22:41.521 | INFO    | prefect.server.api.validation - Cannot validate job variables for work pool my-work-pool because it does not have a base job template
00:22:41.556 | DEBUG   | prefect.server.events.messaging - Publishing event: prefect.work-pool.not-ready with id: e117623b-46c4-451b-abdb-117bdf875ce2 for resource: prefect.work-pool.d279f4bd-d16b-4b54-9d8f-f796c2c03153
00:22:41.560 | DEBUG   | prefect.server.events.services.event_persister - Received event: prefect.work-pool.not-ready with id: e117623b-46c4-451b-abdb-117bdf875ce2 for resource: prefect.work-pool.d279f4bd-d16b-4b54-9d8f-f796c2c03153
```

**Comment by quoimec** [comment]
@parkedwards It's a fresh server with no historical data. The PG database has also been wiped multiple times during testing as I tested both v2 & v3 packages.

I am not using the helm chart, I am managing prefect as a dependency through a currently very light poetry install inside a docker container.

```toml
[tool.poetry.dependencies]
python = "^3.12"
prefect = "^3.0.10"
prefect-kubernetes = "^0.5.1"
```

The docker image is running in K8 as a deployment with the following environment variables:
```tf
PREFECT_API_URL                     = "https://my.domain/api"
PREFECT_UI_API_URL                  = "https://my.domain/api"
PREFECT_SERVER_API_HOST             = "0.0.0.0"
PREFECT_SERVER_API_PORT             = "80"
PREFECT_LOGGING_SERVER_LEVEL        = "DEBUG"
PREFECT_API_DATABASE_CONNECTION_URL = "postgresql+asyncpg://.../prefect"
```

**Comment by quoimec** [comment]
The thing I find weird about this issue is that:
- I can access the UI without issue
- I can create blocks/work pools/variables via the UI without issue
- I can create work pools/variables via Terraform without issue

It is only blocks via terraform that are failing in this way.

**Comment by quoimec** [comment]
I was playing around with the API & UI and I think I may have found something relevant. I noticed that the UI sends the create block request to the `api/block_documents/` endpoint which successfully created the block.

When I send the same payload (with a different name obvs) via python requests to that endpoint, it also successfully creates the block. However, when I change the endpoint to `api/block_documents` - dropping the trailing slash I get the same 405 error. Is there any way to see what endpoint terraform is actually hitting?

API docs list the trailing slash: https://docs.prefect.io/3.0/api-ref/rest-api/server/block-documents/create-block-document

**Comment by parkedwards** [comment]
> Is there any way to see what endpoint terraform is actually hitting?

i think you're onto something, but im not sure it's the trailing slash specifically, since we always append one in a helper

where we construct the endpoint prefix:
* https://github.com/PrefectHQ/terraform-provider-prefect/blob/main/internal/client/block_documents.go#L44

the helper we use to do ^:
* https://github.com/PrefectHQ/terraform-provider-prefect/blob/main/internal/client/util.go#L39

thanks for sharing your server setup, let me noodle on this a bit more

**Comment by parkedwards** [comment]
ah - @quoimec im being silly. you're right - we're not appending the trailing slash here.  testing it locally, my server handles the redirect through a 307, but im wondering if your specific setup with the whitelist is preventing the redirect from being handled properly

```
INFO:     127.0.0.1:54928 - "POST /api/block_documents HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:54928 - "POST /api/block_documents/ HTTP/1.1" 201 Created
```

i'll open up a PR to patch your use case, and we can go from there

**Comment by parkedwards** [comment]
hey @quoimec - give 2.3.2 (just released) a go, and see if that resolves your issue
