### ISSUE TITLE
Github RepoBlocks  not able to reference Github Credentials Block 

### ISSUE THREAD

**Issue by vnagaraj** [PrefectHQ/terraform-provider-prefect#285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v2.3.0 
`+ provider registry.terraform.io/prefecthq/prefect v2.3.0`

### Affected Resource(s)

* prefect_block

### Terraform Configuration Files

```tf
resource "prefect_block" "github_credentials" {
  name      = "gh-credentials"
  type_slug = "github-credentials"

  data = jsonencode({
    "token" = local.git_token    # Reference the value from a Terraform variable
  })

  workspace_id = var.prefect_cloud_workspace_id
  account_id = var.prefect_cloud_account_id
}

# GitHub repository block in Prefect
resource "prefect_block" "github_repo_blocks" {
   name      = "prefect2"
   type_slug = "github-repository"

   data = jsonencode({
    "repository" =  "https://github.com/Butter-Payments/prefect2.git"  # Use the repository URL
    "credentials" = prefect_block.github_credentials.id  # Reference the GitHub credentials block
  })

 workspace_id = var.prefect_cloud_workspace_id
 account_id   = var.prefect_cloud_account_id
}
```

### Expected Behavior

I expect my  github-repository block, "prefect2"  with credentials field  set as the github-credentials block with name as "gh-credentials"

### Actual Behavior

Instead the github-repository block, "prefect2" was created with credentials field set as None

### Steps to Reproduce

1. `terraform apply`
2. Go to Prefect Cloud and inspect the block 

### Important Factoids

Prior to attempting to use terraform, I was creating the same blocks using the Prefect Python SDK, and the block linking was working correctly, and my flow was using the blocks successfully via EKS worker-pool.

### References

https://github.com/PrefectHQ/terraform-provider-prefect/issues/240

**Comment by parkedwards** [comment]
hey @vnagaraj, thanks for raising this issue!  you're coming up against a quirk in our API when it comes to **referencing other blocks**.  our API uses JSON schema to validate objects, but it also expects the [`$ref` syntax](https://json-schema.org/understanding-json-schema/structuring#dollarref) to reference other schemas

in this case, you're creating a `github-repository` block type, in which the `credentials` property will point to a separate `github-credentials` block

**this means that you must point the `credentials` property to a `$ref` expression, like this:**

```hcl
resource "prefect_block" "github_credentials" {
  name      = "gh-credentials"
  type_slug = "github-credentials"

  data = jsonencode({
    "token" = local.git_token # Reference the value from a Terraform variable
  })
}

# GitHub repository block in Prefect
resource "prefect_block" "github_repo_blocks" {
  name      = "prefect2"
  type_slug = "github-repository"

  data = jsonencode({
    "repository" = "https://github.com/Butter-Payments/prefect2.git" # Use the repository URL
    "credentials" = {
      "$ref" = {
        block_document_id = prefect_block.github_credentials.id
      }
    } # Reference the GitHub credentials block
  })
}
```

the important part is:

```hcl
    "credentials" = {
      "$ref" = {
        block_document_id = prefect_block.github_credentials.id
      }
    }
```

it's definitely an obscure quirk that requires one to familiarize themselves with JSON schema expressions.  in any case, you can find some of our documented examples here:

https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/block#example-usage

**Comment by parkedwards** [comment]
hey @mrnvzch - we do call it out here in the `block` / example usage section of the docs that I linked.  if you feel that the wording could be clearer, please feel free to open the PR anyway!

![image](https://github.com/user-attachments/assets/196a2bf3-17b5-43bb-9399-421d05562a9e)

**Comment by mrnvzch** [comment]
Ah those are new docs disted 30 mins ago, the tidbit wasn't there at the time of my previous comment. 
It's clear enough on the docs so no need for a PR - thanks again.
