### ISSUE TITLE
prefect_variable error when upgrading from 2.4.0 to 2.5.0 - prior state: missing expected {

### ISSUE THREAD

**Issue by mch-sb** [PrefectHQ/terraform-provider-prefect#291]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

```
◯ ▲ dataplattform ❱ terraform -v
Terraform v1.9.8
on linux_amd64
```

### Affected Resource(s)

* prefect_variables

### Terraform Configuration Files

```tf
resource "prefect_variable" "environment" {
  name         = "environment"
  value        = var.environment
  workspace_id = prefect_workspace.project_workspace.id
}
```

`var.environment` is a string

### Panic Output

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding
│ "module.prefect_prod_shared[\"prod-ws\"].prefect_variable.environment" from
│ prior state: missing expected {
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding
│ "module.prefect_non_prod_shared[\"non-prod-ws\"].prefect_variable.environment"
│ from prior state: missing expected {
╵
╷
│ Error: Unable to Read Previously Saved State for UpgradeResourceState
│ 
│   with module.prefect_prod_shared["prod-ws"].prefect_variable.environment,
│   on modules/prefect/main.tf line 6, in resource "prefect_variable" "environment":
│    6: resource "prefect_variable" "environment" {
│ 
│ There was an error reading the saved resource state using the current
│ resource schema.
│ 
│ If this resource state was last refreshed with Terraform CLI 0.11 and
│ earlier, it must be refreshed or applied with an older provider version
│ first. If you manually modified the resource state, you will need to
│ manually modify it to match the current resource schema. Otherwise, please
│ report this to the provider developer:
│ 
│ AttributeName("value"): invalid JSON, expected "{", got "prod"
```

### Expected Behavior

Fail to not happen

### Actual Behavior

Fails when running terraform plan with updated prefect-provider-version

### Steps to Reproduce

1. Be on prefect-providerversion 2.4.0
2. Apply changes to `prefect_variables` resources
3. Upgrade to prefect 2.5.0
4. Run `terraform plan` for terraform project with already applied `prefect_variables`

### Important Factoids

I have not tried the actual steps to reproduce, just seeing our previous state at prefect-providerversion 2.4.0 working,
then upgrading to version 2.5.0, and getting the errors mentioned

**Comment by parkedwards** [comment]
resolved by https://github.com/PrefectHQ/terraform-provider-prefect/pull/297
