### ISSUE TITLE
Automated tests for Terraform provider

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/terraform-provider-prefect#30]
The Terraform Plugin Framework includes a test harness for writing integration tests: https://developer.hashicorp.com/terraform/plugin/framework/acctests

Our automated tests would require an external endpoint and secrets, though we can optionally mock out the remote server or use Prefect server for some tests. The Terraform test framework does not support unit testing, so validating errors or warnings may be more difficult (it is not currently possible to check for warnings given a Terraform configuration/run; see: https://github.com/hashicorp/terraform-plugin-testing/issues/69)

There is currently no test coverage for this provider and changes are tested manually on local development machines. It would be preferable to automate these tests, so that we can more easily review and accept pull request contributions.

**Comment by parkedwards** [comment]
https://developer.hashicorp.com/terraform/plugin/testing/acceptance-tests

**Comment by parkedwards** [comment]
also configure helpers for:
* precheck
* sweeps
