### ISSUE TITLE
Flow run crashed with ValueError: Step has unexpected additional keys: branch, repository, access_token

### ISSUE THREAD

**Issue by tejalal** [PrefectHQ/terraform-provider-prefect#321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
Terraform v1.10.2 
on linux_amd64 
+ provider registry.terraform.io/hashicorp/aws v5.80.0 
+ provider registry.terraform.io/prefecthq/prefect v2.12.0 

### Affected Resource(s)
Prefect deployment

### Terraform Configuration Files
```tf
resource "prefect_flow" "flow" {
  name         = "flow-test"
  workspace_id = var.prefect_workspace_id
  tags         = ["test-flow"]
}

resource "prefect_deployment" "deployment" {
  name                     = "test-deployment"
  description              = "test deployment"
  workspace_id            = var.prefect_workspace_id
  flow_id                  = prefect_flow.flow.id
  entrypoint               = "flows/flow.py:my-flow"
  tags                     = ["test", "dev"]
  enforce_parameter_schema = false  
  
parameters = jsonencode({
    "parameters_uri" : "s3-path",
    "chunk_size" : 5000
  })
  
  parameter_openapi_schema = jsonencode({
    "type" : "object",
    "properties" : {
      "parameters_uri" : { "type" : "string" }
      "chunk_size"     : { "type" : "integer" }
    }
  })

  path                = "/flows"
  paused              = false
  pull_steps = [
  {
      type         = "git_clone"
      repository   = "https://my-git-repo.git"
      branch       = "main"
      access_token = var.github_token
  }
  ]
  version             = "v1.1.1"
  work_pool_name      = var.work_pool_name
  work_queue_name     = "default"
}
```

### Debug Output

Flow could not be retrieved from deployment.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 160, in run_steps
    step_output = await run_step(step, upstream_outputs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 116, in run_step
    raise ValueError(
_ValueError: Step has unexpected additional keys: branch, repository, access_token_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 437, in retrieve_flow_then_begin_flow_run
    else await load_flow_from_flow_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/deployments.py", line 307, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 188, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running access_token
```

### Expected Behavior
The flow run should run without a crash or failure.

### Actual Behavior
The flow is crashing with `ValueError: Step has unexpected additional keys: branch, repository, access_token`. It is failing the pull_steps, is there anything that needs to be added to pull_steps? The documentation has only four fields to pull the flow code in the pull_steps that is type, branch, repository, and access_token [https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/deployment#type-1](https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/deployment#type-1)

### Steps to Reproduce
1. `terraform apply`
2. Run flow from the Prefect UI

**Comment by mitchnielsen** [comment]
Thanks for the report here @tejalal, I'm digging into this and it looks like the `pull_steps` payload may be malformed in the provider. I'll follow up with any updates/PRs.

**Comment by mitchnielsen** [comment]
That was exactly it, good eye. Already working on a PR, should be up soon 👍🏼

**Comment by tejalal** [comment]
Hi @mitchnielsen, is it ready to use in 2.12.0 or a new version is to be released.
