### ISSUE TITLE
Prefect Flows and Deployments 405 Response 

### ISSUE THREAD

**Issue by thanh-tran-techx** [PrefectHQ/terraform-provider-prefect#328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/prefecthq/prefect v2.12.3

### Affected Resource(s)

- prefect_flow
- prefect_deployment

### Terraform Configuration Files

```tf
resource "prefect_flow" "extraction" {
  name = "extraction-flow-terraform"
  tags = ["jobType=Extraction"]
}

resource "prefect_deployment" "extraction" {
  name                     = "extraction-deployment-terraform"
  description              = "Extraction Flow for some table, Created by Terraform"
  flow_id                  = prefect_flow.extraction.id
  entrypoint               = "flows/extraction_flow.py:extraction_flow"
  tags                     = ["jobType=Extraction"]
  enforce_parameter_schema = true
  storage_document_id      = data.prefect_block.code-bucket.id
  parameter_openapi_schema = jsonencode({
    "type" : "object",
    "properties" : {
      "db_name" : { "type" : "string" }
      "table_name" : { "type" : "string" }
      "bucket_name" : { "type" : "string" }
    }
  })
  version        = "1"
  work_pool_name = "onpremise"
}
```

### Output

```
Could not create flow, unexpected error: failed to create flow: status code=405 Method Not Allowed, error={"detail":"Method Not Allowed"}
```

### Server Debug Log
```
13:26:35.251 | INFO    | uvicorn.access - 10.9.225.204:24754 - "POST /api/flows HTTP/1.1" 307
13:26:35.323 | INFO    | uvicorn.access - 10.9.225.204:24754 - "GET /api/flows/ HTTP/1.1" 405
```

### Steps to Reproduce

1. `terraform apply -auto-approve`

### Important Factoids

This seem to be the problem with golang http redirect does not respect 307 response code, and instead send a GET request instead of POST requests.

### References

* #284

**Comment by mitchnielsen** [comment]
Hi @thanh-tran-techx, thanks for reaching out.

Looks like you're running Prefect Server yourself (based on the included server logs). Is that right?

I ask because I wasn't able to replicate the problem here, and I tried on Prefect Cloud and a self-hosted Prefect Server running locally. 

Do you happen to be running a reverse proxy in front of Prefect?

I agree this initially looks like https://github.com/PrefectHQ/terraform-provider-prefect/pull/287 would fix this, but I would have expected to be able to replicate this error first.

**Comment by thanh-tran-techx** [comment]
Hi @mitchnielsen,

Thank you for reaching out to me. It seem like fast API does not respect the header `x-forwarded-proto` and `x-forwarded-for` from reverse proxy (AWS ALB in this case)

Here the redirect chain when using python requests:
POST -> 307 -> (location set to https) -> POST -> 201 (I manually inject x-forwarded-proto in this case)

I put a middleware in front of the api for the server and found this redirect chain:
POST -> 307 -> (location set to http) -> 302 (ALB automatically redirect to https) -> GET -> 405

I logged all the header and can confirm that it is not issue with ALB redirections, they do inject the correct headers. I think #287 encounter the same issues.

I will post a separate bugs on FastAPI or Prefect server up on further confirmation if this is due to setting in Prefect Server or FastAPI.

**Comment by thanh-tran-techx** [comment]
Update 2:
It seem that FORWARDED_ALLOW_IPS is the culprits.
Header used:
```
"x-forwarded-for": "10.9.225.62:45658",
"x-forwarded-proto": "https",
"x-forwarded-port": "443",
```
With FORWARD_ALLOW_IPS set to bogus ip address (not 127.0.0.1)
```
Rebuild Method: POST
307
{
  "date": "Tue, 17 Dec 2024 18:48:19 GMT",
  "server": "uvicorn",
  "content-length": "0",
  "location": "http://test.prefect.io/api/flows/",
  "connection": "keep-alive"
}
```
With FORWARD_ALLOW_IPS set to 127.0.0.1 or "*"
```
Rebuild Method: POST
307
{
  "date": "Tue, 17 Dec 2024 18:48:19 GMT",
  "server": "uvicorn",
  "content-length": "0",
  "location": "https://test.prefect.io/api/flows/",
  "connection": "keep-alive"
}
```

I can confirm that this is an issue with the default settings of uvicorn. No action maybe needed from your side @mitchnielsen .
But if we can avoid the redirection altogether since `prefect-server` may change settings to not forwarded at anytime :D
