### ISSUE TITLE
Work pool created with Terraform does not starts the worker automatically

### ISSUE THREAD

**Issue by teja-seer** [PrefectHQ/terraform-provider-prefect#337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
Terraform v1.10.2
on linux_amd64
provider registry.terraform.io/hashicorp/aws v5.80.0
provider registry.terraform.io/prefecthq/prefect v2.12.0

### Affected Resource(s)
Prefect Work Pool

### Terraform Configuration Files
```tf
resource "prefect_work_pool" "work-pool" {
    name              = var.work_pool_name
    type              = "ecs"
    workspace_id     = var.prefect_workspace_id
    paused            = false
    base_job_template = jsonencode(base_job_json_template)
```

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
The work pool created with Terraform should be in a ready state (up and running with at least one worker). The Terraform resource does create the work pool. I have a requirement that there shouldn't be a need to start the worker from the terminal with $prefect worker start -p 'my-worker' --type ecs

### Actual Behavior
The work pool created with Terraform is not in the ready state.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
No

### References
NA

**Comment by jamiezieziula** [comment]
Hi @teja-seer - this resource is only responsible for creating the workpool, not the worker itself. You will still need to deploy your worker to ECS either manually or by using the AWS terraform provider.
