### ISSUE TITLE
Add support for Automations

### ISSUE THREAD

**Issue by TaliaSRTR** [PrefectHQ/terraform-provider-prefect#52]
It would be convenient to be able to manage these resources like Automations and Service Accounts via the Terraform provider. Managing them via code as opposed to the UI (or even the API) would be nice because these kinds of resources are often:

1. Relatively static
2. Configured very similarly from one to the next, and so would lend themselves to being built out via custom Terraform modules

In the case of Service Accounts, these objects also generate sensitive output that needs to be pushed to other secrets stores like AWS Secrets Manager, for example. Making changes to these resources (e.g. refreshing API tokens) and having the changes instantly propagated to your secrets vault/manager of choice would remove some of the tedium of having to do this kind of stuff manually.

**Comment by parkedwards** [comment]
Great connecting today - we'll kick tires on Automations, and Service Accounts were added in #49, with key rotation handled in #73

**Comment by dacreify** [comment]
Automations would be extremely valuable. For example, configuring notifications for flows that run longer than expected in a standardized and reusable way.

**Comment by taylor-curran** [comment]
I have another customer strongly asking for automations to be supported by the terraform provider.

**Comment by mitchnielsen** [comment]
With Service Accounts addressed in https://github.com/PrefectHQ/terraform-provider-prefect/issues/27 and https://github.com/PrefectHQ/terraform-provider-prefect/issues/80, I'm going to modify the issue title to focus on Automations so we can track this more accurately 👍🏼

**Comment by mitchnielsen** [comment]
As a breadcrumb, Eddie has created https://github.com/PrefectHQ/terraform-provider-prefect/issues/177 to scope the work to add this.

**Comment by parkedwards** [comment]
released in `v2.8.0`

https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/automation
