### ISSUE TITLE
Publish signed Prefect Cloud 2 release on Terraform Registry

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/terraform-provider-prefect#9]
Instructions for publishing are in HashiCorp's documentation: https://developer.hashicorp.com/terraform/registry/providers/publishing#publishing-to-the-registry

Depends on #12

**Comment by jawnsy** [comment]
Looks like there's a [legal angle](https://developer.hashicorp.com/terraform/registry/providers/publishing#terms-of-use) to this too, will loop in Brian on their [Terms of Use](https://registry.terraform.io/terms)

**Comment by didopop3** [comment]
Hi, @jawnsy any updates on this of if you need any help with the regestry? Our team is hoping to use this in our project soon :D

**Comment by ConstantinoSchillebeeckx** [comment]
Any update on this by chance?

**Comment by parkedwards** [comment]
there is an alpha published to the registry now so we'll be closing this issue. but note that we're still actively developing and fixing issues prior to the first stable release
